config/routes.rb
GalCivBoardGame::Application.routes.draw do

  root 'messages#index'

  get 'description' => 'pages#description' 
  get 'rules'       => 'pages#rules'  
  get 'map'         => 'pages#map'  
  get 'policy'      => 'pages#policy' 
  get 'technologies'=> 'pages#technologies'
  get 'planets'     => 'pages#planets' 
  get 'spaceships'  => 'pages#spaceships' 
  get 'downloads'   => 'pages#downloads' 
  get 'feedback'    => 'feedbacks#index'
  get 'contacts'    => 'pages#contacts'
  
  get "auth/:provider/callback" => "sessions#create"
  get "auth/:provider/oauth2callback" => "session#create"
  get "signout" => "sessions#destroy"

  resources :messages
  resources :comments, only: [:create, :destroy]
  resources :feedbacks, only: [:create, :destroy]
  resources :users, only: [:update, :destroy, :show, :index]

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true, length: { maximum: 255 }
  validates :message_id, presence: true
  validates :user_id, presence: true
  default_scope -> { order('created_at DESC') }
  belongs_to :message
  belongs_to :user
  include SmartLinks
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  EMAIL_REGEXP = /\A([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})\z/  
  belongs_to :user
  validates :content, presence: true, length: { maximum: 255 }
  validates :mark, allow_blank: true, inclusion: { in: [1, 2, 3, 4, 5] }
  validates :email, allow_blank: true, format: { with: EMAIL_REGEXP }
  validates :user_id, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :title, presence: true, length: {maximum: 25}
  validates :content, presence: true
  PATH_REGEX = /\A[a-z0-9-]{2,25}\z/ 
  validates :url_title, presence: true, format: { with: PATH_REGEX },
                        uniqueness: true
  default_scope -> { order('created_at DESC') }
  has_many :comments, dependent: :destroy
  include SmartLinks
  
  def to_param
    "#{url_title.parameterize}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  PROVIDERS_LIST = %w(facebook google-oauth2 vkontakte github)
  ACCESS_LIST = %w(user moderator administrator baned deleted)
  URL_REGEXP = /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?\z/  
  AVATAR_REGEXP = /\Ahttps?.*(jpeg|jpg|gif|png)\z/
  before_create { self.access = "user" }
  validates :uid, presence: true
  validates :name, presence: true, length: { maximum: 32}
  validates :provider, inclusion: { in: PROVIDERS_LIST}
  validates :access, inclusion: { in: ACCESS_LIST }, on: :save
  validates :link, allow_blank: true, format: { with: URL_REGEXP }
  validates :image_link, allow_blank: true, format: { with: AVATAR_REGEXP }
  has_many :comments, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @message = Message.find_by_id(params[:message_id])
    parameters = params.require(:comment).permit(:user_id, :content)
    @message.comments.create( parameters )
    flash.now[:notice] = "Комментарий успешно опубликован!"
    respond_to do |format|
      format.html { redirect_to :back }
      format.js do
        @comments = @message.comments.paginate(page: params[:page],:per_page => 10)
        @comment =  @message.comments.new
      end
    end
  end
  
  def destroy

  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :admin, only: [:new, :edit, :upadte, :destroy]
  
  def new
  end
  
  def destroy
  end
  
  def show
    @message = Message.find_by_url_title(params[:id])
    @comment =  @message.comments.new
    @comments = @message.comments.paginate(page: params[:page],:per_page => 10)
  end
  
  def index
    @messages = Message.paginate(page: params[:page], :per_page => 5)
  end
  
  def edit
    
  end
  
  def update
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def news
  end
  
  def description
  end
  
  def rules
  end
  
  def map
  end
  
  def policy  
  end
  
  def technologies
  end
  
  def planets
  end
  
  def spaceships
  end
  
  def downloads
  end
  
  def feedback
  end
  
  def contacts
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  
  def create
    auth = request.env["omniauth.auth"]
    @user = User.find_or_create_by uid: auth.uid.to_s, 
                                        provider: auth.provider do |user|
      user.name = auth.info.name
      user.image_link = auth.info.image
      user.link = auth.extra.raw_info.link 
    end
    check_for_updates @user unless @user.new_record?
    reset_session
    session[:user_id] = @user.id 
    redirect_to_back
  end

  def destroy
    session[:user_id] = nil
    redirect_to_back
  end
  
  private 
  def redirect_to_back(default = root_path)
    if !request.env["HTTP_REFERER"].blank? and \
    request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back
    else
      redirect_to default
    end
  end
    
  def check_for_updates(user)
    auth = request.env["omniauth.auth"]
    user.name = auth.info.name unless user.name == auth.info.name 
    user.image_link = auth.info.image unless user.image_link == auth.info.image
    unless user.link = auth.extra.raw_info.link
      user.link = auth.extra.raw_info.link 
    end
    user.save if user.changed?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  BGCOUNT = 5
  
  def full_title(page_title)
    title = "Космическая Федерация. Настольная игра"
    title + ( page_title.empty? ? "" : " | #{page_title}")
  end
  
  def random_bg
    "backgrounds/bg#{rand(5)}.jpg"
  end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
.comment
  .comment_title
    = image_tag comment.user.image_link, size: "50x50", class: "comment_avatar"
    %span.comment_author
      - if comment.user.link.blank?
        = comment.user.name
      - else
        = link_to comment.user.name, comment.user.link, target: '_tab'
      = " | "
      = comment.created_at.strftime("%H:%M:%S  %d.%m.%Y")
  .comment_content= raw(comment.content)
%br

app/views/comments/create.js.erb
$(".comments_list").html("<%= \
	                  escape_javascript(render 'messages/comments_content')%>")									
$("h2").html("<%= "Комментариев: #{@message.comments.count}"%>")
document.getElementById('comment_text_area').value='';									                    

app/views/feedbacks/index.html.haml
- provide(:title, "Отзывы")
%h1 Отзывы
%p Here will be some page later
%p 1
%p 2
%p 3
%p 4
%p 5

app/views/layouts/_footer.html.haml
.footer
  .left_footer
  .right_footer
  .center_footer
    .left_link
      Все права на символику принадлежат компании
      = link_to 'StarDock', "http://www.stardock.com/", target: '_tab' 
    .right_link= link_to 'Контакты', contacts_path

app/views/layouts/_header.html.haml
.header
  .left_logo
    = image_tag("header/Ethic_Evil.png")
    = image_tag("header/WarParty.png")
  .right_logo
    = image_tag("header/Industrialist.png")
    = image_tag("header/Ethic_Good.png")
  .center_logo= image_tag("header/Logo.png")

app/views/layouts/_menu.html.haml
.menu
  %ul 
    %li= link_to image_tag("menu/news.png"), root_path,        class: "news"
    %li= link_to image_tag("menu/desc.png"), description_path, class: "desc"
    %li= link_to image_tag("menu/rules.png"), rules_path,      class: "rules"
    %li= link_to image_tag("menu/map.png"), map_path,          class: "map"
    %li= link_to image_tag("menu/policy.png"), policy_path,    class: "policy"
    %li= link_to image_tag("menu/tech.png"), technologies_path, class: "tech"
    %li= link_to image_tag("menu/planets.png"), planets_path,  class: "planets"
    %li= link_to image_tag("menu/ships.png"), spaceships_path, class: "ships"
    %li= link_to image_tag("menu/files.png"), downloads_path,  class: "files"
    %li= link_to image_tag("menu/fb.png"),  feedback_path,     class: "fb"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag "application", "data-turbolinks-track" => true 
    = favicon_link_tag 
    = csrf_meta_tags 
  %body{ background: image_path(random_bg) }
    .content
      = render 'layouts/header'
      .section
        = render 'layouts/menu'
        .article
          = yield 
          = debug(params) if Rails.env.development? 
    = render 'layouts/footer'

app/views/messages/_comment_form.html.haml
= form_for(@comment, remote: true) do |f|
  .field= f.hidden_field :user_id, value: current_user.id
  .label= f.label "text_area", "Текст комментария"
  .area= f.text_area :content, size: "37x4", wrap: "soft",             
    required: true, id: "comment_text_area"
  = hidden_field_tag :message_id, @message.id
  = f.submit "Отправить", class: "comment_button"
    

app/views/messages/_comments_content.html.haml
.comments
  = will_paginate @comments, previous_label: 'Предыдущая',
      next_label: 'Следующая', params: { anchor: "comments" } 
  = render "shared/flash"
  = render @comments 
  = will_paginate @comments, previous_label: 'Предыдущая',
      next_label: 'Следующая', params: { anchor: "comments" } 

app/views/messages/_created.html.haml
.message_created
  %div
    = image_tag "message/created.png"
    = object.created_at.strftime("Cоздано %d.%m.%Y")
  %div
    - if object.created_at != object.updated_at
      = image_tag "message/changed.png"
      = object.updated_at.strftime("Отредактировано %d.%m.%Y")

app/views/messages/_message.html.haml
%li
  .message_header
    .message_title= link_to message.title, message
    = render "created", object: message
  .message_content
    = message.content.truncate(500, omission: "...", separator: ' ')
  .message_footer
    .more
      = image_tag "message/lup.png"
      = link_to "Подробнее", message
    .comments_count
      = image_tag "message/comment.png"
      = link_to "Комментариев: #{message.comments.count}",
          message_path(message, anchor: "comments")
  .message_border
    .left_border
    .right_border
    .center_border

app/views/messages/index.html.haml
- provide(:title, "Новости")
%h1 Новости сайта
%ul.messages= render @messages
= will_paginate previous_label: 'Предыдущая', next_label: 'Следующая'

app/views/messages/show.html.haml
- provide(:title, @message.title)
%h1= @message.title
.message_content= raw(@message.content)
.message_panel
  %a{ name: "comments" }  
  - if current_user
    #user_info
      = render "users/info", object: current_user
      = render "comment_form"
  - else
    #sign_in= render "shared/signin"
  = render "created", object: @message
  %h2 Комментариев: #{@message.comments.count}
.comments_list= render 'comments_content'

app/views/pages/contacts.html.haml
- provide(:title, "Контакты")
%h1 Контакты
%p Here will be some page later
%p 1
%p 2
%p 3
%p 4
%p 5

app/views/pages/description.html.haml
- provide(:title, "Описание")
%h1 Описание игры и игровых расс
%p Here will be some page later
%p 1
%p 2
%p 3
%p 4
%p 5

app/views/pages/downloads.html.haml
- provide(:title, "Скачивание материалов")
%h1 Скачивание материалов игры
%p Here will be some page later
%p 1
%p 2
%p 3
%p 4
%p 5

app/views/pages/map.html.haml
- provide(:title, "Карта")
%h1 Обзор глобальной карты
%p Here will be some page later
%p 1
%p 2
%p 3
%p 4
%p 5

app/views/pages/planets.html.haml
- provide(:title, "Планеты и сооружения")
%h1 Типы и классы планет
%p Here will be some page later
%p 1
%p 2
%p 3
%p 4
%p 5

app/views/pages/policy.html.haml
- provide(:title, "Политика и этика")
%h1 Политика и этика 
%p Here will be some page later
%p 1
%p 2
%p 3
%p 4
%p 5

app/views/pages/rules.html.haml
- provide(:title, "Правила")
%h1 Основные правила игры
%p Here will be some page later
%p 1
%p 2
%p 3
%p 4
%p 5

app/views/pages/spaceships.html.haml
- provide(:title, "Корабли и снаряжение")
%h1 Космические корабли и их сняряжение
%p Here will be some page later
%p 1
%p 2
%p 3
%p 4
%p 5

app/views/pages/technologies.html.haml
- provide(:title, "Технологии")
%h1 Древа технологий 
%p Here will be some page later
%p 1
%p 2
%p 3
%p 4
%p 5

app/views/shared/_flash.html.haml
.flash
  - flash.each do |key, value| 
    %div{ class: "flash_#{key} " }= value 

app/views/shared/_signin.html.haml
%p Войдите что бы оставлять комментарии
= link_to image_tag("omniauth_icons/facebook.png"), "/auth/facebook"
= link_to image_tag("omniauth_icons/google.png"), "/auth/google_oauth2"
= link_to image_tag("omniauth_icons/vk.png"), "/auth/vkontakte"
= link_to image_tag("omniauth_icons/github.png"), "/auth/github"

app/views/users/_info.html.haml
- unless object.image_link.blank?
  = image_tag object.image_link, size: "50x50"
-else 
  = image_tag "no_avatar.png", size: "50x50"
- if object.link.blank?
  = object.name
- else
  = link_to object.name, object.link, target: '_tab'
= " | "
= link_to "Выход", signout_path